### PR TITLE
Allow body to be empty

### LINKED ISSUE #5: 304, 204 etc response with Accept-Encoding: gzip
Doesn't this still write the footer because of the gzip writer .Close()?

### PR DESCRIPTION
**Pull request by Thomasdezeeuw**
This change allows the body to be completely empty, that means without
gzip headers. This a requirement with status codes that do not allow
for a body, for example 204 No Content.

It also changes to a lazily initialise method for the gzip writer.

Fixes #5.

### CODE REVIEW

**Comment by Thomasdezeeuw** [comment]
I've updated the code to run on < Go 1.7.

**Comment by Thomasdezeeuw** [comment]
Ping.

**Comment by jprobinson** [comment]
Sorry for the delay, we had a change of repo ownership in the past week and this fell through the gaps.

This looks good to me. Thanks for contributing!

**Comment by adammck** [comment]
Thanks for adopting this one, @jprobinson! (And sorry, @Thomasdezeeuw, for leaving you hanging.)

**Comment by jprobinson** [comment]
Just to add an update...we found this introduced a bug for any handler calling `WriteHeader` before writing the actual body to the response.

We ended up altering the library in #19 to still allow empty responses, but _only_ for 204 and 304.

**Comment by Thomasdezeeuw** [comment]
Thanks.

**Pull request merged**
